// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ6Zk0ufa9ZyDPPCSqINufD1_mzkzpU-w',
    appId: '1:1023182869713:web:ec6359c03985473e0461f0',
    messagingSenderId: '1023182869713',
    projectId: 'safebite-database',
    authDomain: 'safebite-database.firebaseapp.com',
    storageBucket: 'safebite-database.firebasestorage.app',
    measurementId: 'G-4SNG7ZHD1G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADQbBO1a5ynoLJmYEurAgmvt30zhAVREI',
    appId: '1:1023182869713:android:c35794da8dac4cea0461f0',
    messagingSenderId: '1023182869713',
    projectId: 'safebite-database',
    storageBucket: 'safebite-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUn2nZ2Ha8Ny5jjcodf8cR3C6Lzj10KIM',
    appId: '1:1023182869713:ios:e338d215bbbe3fb40461f0',
    messagingSenderId: '1023182869713',
    projectId: 'safebite-database',
    storageBucket: 'safebite-database.firebasestorage.app',
    iosBundleId: 'com.example.safebite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUn2nZ2Ha8Ny5jjcodf8cR3C6Lzj10KIM',
    appId: '1:1023182869713:ios:e338d215bbbe3fb40461f0',
    messagingSenderId: '1023182869713',
    projectId: 'safebite-database',
    storageBucket: 'safebite-database.firebasestorage.app',
    iosBundleId: 'com.example.safebite',
  );
}
